title: Cooptech
baseurl: ""
url: "https://cooptech.fr"
collections:
  members:
    output: true
    layout: member
    permalink: /societes/:name
  posts:
    permalink: /nos-actions/:year/:month/:title
exclude:
  - "_members/TEMPLATE"
