title: Cooptech
baseurl: ""
url: "https://cooptech.fr"
collections:
  members:
    output: true
    layout: member
    permalink: /members/:name
  posts:
    permalink: /actions/:year/:month/:title
exclude:
  - "_members/TEMPLATE"
